#Extent Report
extent.reporter.spark.start=true
extent.reporter.spark.out=Reports/Spark.html
  
  
#PDF Report
extent.reporter.pdf.start=true
extent.reporter.pdf.out=PdfReport/ExtentPdf.pdf
  
#HTML Report
extent.reporter.html.start=true
extent.reporter.html.out=HtmlReport/ExtentHtml.html

#Excel Report  
extent.reporter.excel.start=true
extent.reporter.excel.out=ExcelReport/ExtentExcel.xlsx
  
#FolderName
basefolder.name=target/Reports/ExtentReports/SparkReport_
basefolder.datetimepattern=d_MMM_YY HH_mm_ss
  
#Screenshot
screenshot.dir=../Extent_Reports_ScreenshotDir
#screenshot.rel.path=../ExtentReportScreenshotDir/
  
#Base64
extent.reporter.spark.base64imagesrc=true
  
#System Info
systeminfo.os=windows
systeminfo.version=11
